centence = input('문장을 입력하세요: ')
print('#' * 10)
print(f'대문자 변환: {centence.upper()}')
print(f'소문자 변환: {centence.lower()}')
print(f'문자열 길이: {len(centence)}')
print(f'공백으로 분리 {centence.split()}')
print(f'마침표로 분리 {centence.split(".")}')
print(f'o의 위치 {centence.index("o")}')
print(f'o의 개수 {centence.count("o")}')
print(f'Python을 AI로 교체: {centence.replace("Python", "AI")}')
